from app import app
c = app.test_client()
r = c.get('/api/classified_mode?mode=balanced&sort_by=account_name&sort_dir=asc')
print('resp1', r.status_code)
j = r.get_json()
print('count1', j.get('count'), 'len1', len(j.get('data') or []))
r2 = c.get('/api/classified_mode?mode=balanced')
print('resp2', r2.status_code)
j2= r2.get_json()
print('count2', j2.get('count'), 'len2', len(j2.get('data') or []))
